name: Empty Variable Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  check-empty-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies (client)
        working-directory: ./client
        run: npm install

      - name: Run empty variable check
        run: node scripts/checkEmpty.js